### ISSUE TITLE
获取PHPDoc的正则在解析的时候会出现\r，建议正则修改！

### ISSUE THREAD

**Issue by zhmuyu** [zlikavac32/php-enum#4]
```php

$regex = '/@method\s+static\s+[^\s]+\s+(.+)\s*\r(?:\(\))?/';

```

**Comment by zhmuyu** [comment]
助手函数resolveMethodsFromDocblock！

**Comment by zlikavac32** [comment]
@zhmuyu Could you give a line on which this regex does not produce desired result?

**Comment by zlikavac32** [comment]
@zhmuyu Ah, yea, I managed to translate. `\r` is capured as well, right?

**Comment by zlikavac32** [comment]
@zhmuyu Does new code work for you?

**Comment by zhmuyu** [comment]
> @zhmuyu Does new code work for you?

是的，可以使用！
